services:
  app:
    build: .
    ports: #read ports from .env
      - "${APP_PORT}:8080"
    env_file: #configure go-app
      - config.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    command: #max connections from .env
      - postgres
      - -c
      - max_connections=${POSTGRES_MAX_CONNECTIONS}
    env_file: #configure postgreSQL
      - config_user.env
    ports: #and postgres port also from .env
      - "${POSTGRES_PORT}:5432"
